name: Build Development Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 22 * * 5'  # Runs every Friday at 10 PM

permissions:
  contents: write

jobs:
  manual_trigger:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Tag
        id: gen_tag
        run: echo "RELEASE_TAG=dev-$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV  # Using the generated tag

      - name: Create Empty Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          body_path: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: main
          draft: false

    outputs:
      release_id: ${{ steps.release.outputs.id }}

  build:
    runs-on: ubuntu-latest
    needs: manual_trigger
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Checkout Armbian Repository
        uses: actions/checkout@v3
        with:
          repository: armbian/build
          ref: main
          path: build

      - name: Set env
        shell: bash
        run: |  
          echo "release=jammy" >> $GITHUB_ENV  
          echo "build-minimal=no" >> $GITHUB_ENV  
          echo "build-desktop=yes" >> $GITHUB_ENV  
          echo "desktop-environment=gnome" >> $GITHUB_ENV  
          echo "desktop-environment-config-name=config_base" >> $GITHUB_ENV  
          echo "expert=yes" >> $GITHUB_ENV

      - name: Build Image
        shell: bash
        run: |  
          cd ./build  
          touch .ignore_changes  

      - name: Upload Armbian Development Image
        uses: amazingfate/armbian-compile-action@main
        with:
          board: x86  # Board for the x86 development image
          flavor: ubuntu  # Flavor of the development image
          release-id: ${{ needs.manual_trigger.outputs.release_id }}  # ID of the release created in the previous step
          github-token: ${{ secrets.GITHUB_TOKEN }}
