name: Build Development Image

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  manual_trigger:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Tag
        id: gen_tag
        run: echo "RELEASE_TAG=dev-$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

      - name: Create Empty Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}  # Usamos la etiqueta generada
          body_path: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: main
          draft: false

    outputs:
      release_id: ${{ steps.release.outputs.id }}

  build:
    runs-on: ubuntu-latest
    needs: manual_trigger
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set env
        shell: bash
        run: |  
          echo "release=jammy" >> $GITHUB_ENV  
          echo "build-minimal=no" >> $GITHUB_ENV  
          echo "build-desktop=yes" >> $GITHUB_ENV  
          echo "desktop-environment=gnome" >> $GITHUB_ENV  
          echo "desktop-environment-config-name=config_base" >> $GITHUB_ENV  
          echo "expert=yes" >> $GITHUB_ENV

      - name: Build Image
        shell: bash
        run: |  
          cd ./build  
          touch .ignore_changes  

      - name: Upload Armbian Development Image
        uses: amazingfate/armbian-compile-action@main
        with:
          branch: main  # Rama del repositorio de Armbian
          board: x86  # Placa para la imagen de desarrollo x86
          flavor: ubuntu  # Sabor de la imagen de desarrollo
          release-id: ${{ needs.manual_trigger.outputs.release_id }}  # ID del lanzamiento creado en el paso anterior
          github-token: ${{ secrets.GITHUB_TOKEN }}
